# Generated by Django 3.0.3 on 2020-11-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('answer', models.CharField(max_length=40)),
                ('definition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.IntegerField()),
                ('description', models.TextField()),
                ('microscopy', models.CharField(max_length=40)),
                ('cell_type', models.CharField(max_length=45)),
                ('component', models.CharField(max_length=35)),
                ('doi', models.CharField(max_length=25)),
                ('organism', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=70)),
                ('category', models.CharField(max_length=10)),
                ('imagefield', models.CharField(max_length=15)),
                ('points', models.IntegerField()),
                ('n_answer', models.IntegerField()),
                ('n_image', models.IntegerField()),
            ],
        ),
    ]
