# Generated by Django 3.0.3 on 2020-11-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzapp', '0002_authuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('score', models.IntegerField()),
            ],
        ),
    ]
