# Generated by Django 3.0.3 on 2020-11-11 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzapp', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quizzapp.Answers'),
        ),
        migrations.AddField(
            model_name='questions',
            name='image',
            field=models.ManyToManyField(blank=True, related_name='question', to='quizzapp.Images'),
        ),
    ]
